### ISSUE TITLE
Using ui elements within selectors for other ui definitions in views?

### ISSUE THREAD

**Issue by radkodinev** [marionettejs/backbone.marionette#1836]
For example:

```
ui:
  form: ".some-form"
  inputs: "@ui.form input" // instead of ".some-form input"
```

Or event better (and less confusing when using CoffeeScript) - without the `ui.` part:

```
ui:
  form: ".some-form"
  inputs: "@form input"
  disabledInputs: "@inputs:disabled"
  checkboxes: "@inputs[type=checkbox]"
```

The aim is to avoid duplication and shorten declarations.
