### ISSUE TITLE
Add class events for the api

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#1973]
The v1 api does will be a port of the existing docs, with the goal of reaching parity. With that said, as we improve the api we want to include **events**. Events are both the events that are emitted by the class and the place of origin for the events. 

We will use this issue to track our progress on a class-by-class basis.

#### Classes
- [ ] application
- [ ] approuter
- [ ] behavior  
- [ ] collectionview    
- [ ] compositeview   
- [ ] controller 
- [ ] itemview   
- [ ] layoutview
- [ ] module
- [ ] objec
- [ ] region
- [ ] regionManager 
- [ ] view 

----

We should follow this standard: http://usejsdoc.org/tags-event.html and be consistent with other jsdoc conventions.

```yaml
events: 
   -
      name: "before:attach"

      description: |
         Fired when we attach a view to the document
         
         @event before:attach
         @param {Marionette.View} view - the view that's attached

      examples:
         -
             name: Using before:attach with jQuery
             example: |
                oh yea
```

----

We'll also document where events are fired and that will be different

```js

// @fires before:attach
this.triggerMethod('before:attach');
```
